### ISSUE TITLE
Change che docstring color

### ISSUE THREAD

**Issue by arichiardi** [overtone/emacs-live#211]
Can I ask if there is a way to change the docstring color back as it was?

Just a hint on where to touch...

![selection_017](https://cloud.githubusercontent.com/assets/1724788/8579480/27132854-25b5-11e5-94ba-61a0ee5eb714.png)

**Comment by arichiardi** [comment]
Probably thit question can be better answered in `clojure-mode`, closing 😀

**Comment by hungcodon** [comment]
Gửi từ điện thoại thông minh BlackBerry 10.                                                                                                                                                                                                                Từ: Andrea RichiardiĐã gửi: 2:13 CH Thứ sáu, ngày 17 tháng hai năm 2017Đến: overtone/emacs-liveTrả lời đến: overtone/emacs-liveCc: SubscribedChủ đề: Re: [overtone/emacs-live] Change che docstring color (#211)Closed #211.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/overtone/emacs-live","title":"overtone/emacs-live","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/overtone/emacs-live"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #211."}],"action":{"name":"View Issue","url":"https://github.com/overtone/emacs-live/issues/211#event-966387920"}}}
